// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: poet.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPoet = `-- name: CreatePoet :one
INSERT INTO poets (name, bio, time_period) VALUES ($1, $2, $3) RETURNING id,name,bio,time_period
`

type CreatePoetParams struct {
	Name       pgtype.Text    `json:"name"`
	Bio        pgtype.Text    `json:"bio"`
	TimePeriod NullTimePeriod `json:"time_period"`
}

type CreatePoetRow struct {
	ID         pgtype.UUID `json:"id"`
	Name       string      `json:"name"`
	Bio        string      `json:"bio"`
	TimePeriod TimePeriod  `json:"time_period"`
}

func (q *Queries) CreatePoet(ctx context.Context, arg CreatePoetParams) (CreatePoetRow, error) {
	row := q.db.QueryRow(ctx, createPoet, arg.Name, arg.Bio, arg.TimePeriod)
	var i CreatePoetRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.TimePeriod,
	)
	return i, err
}

const getPoetById = `-- name: GetPoetById :one
SELECT id,name,bio,time_period FROM poets WHERE id = $1 LIMIT 1
`

type GetPoetByIdRow struct {
	ID         pgtype.UUID `json:"id"`
	Name       string      `json:"name"`
	Bio        string      `json:"bio"`
	TimePeriod TimePeriod  `json:"time_period"`
}

func (q *Queries) GetPoetById(ctx context.Context, id pgtype.UUID) (GetPoetByIdRow, error) {
	row := q.db.QueryRow(ctx, getPoetById, id)
	var i GetPoetByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.TimePeriod,
	)
	return i, err
}

const getPoets = `-- name: GetPoets :many
SELECT id,name,bio,time_period FROM poets
`

type GetPoetsRow struct {
	ID         pgtype.UUID `json:"id"`
	Name       string      `json:"name"`
	Bio        string      `json:"bio"`
	TimePeriod TimePeriod  `json:"time_period"`
}

func (q *Queries) GetPoets(ctx context.Context) ([]GetPoetsRow, error) {
	rows, err := q.db.Query(ctx, getPoets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPoetsRow
	for rows.Next() {
		var i GetPoetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Bio,
			&i.TimePeriod,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
